<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="2" passed="1">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="52" started-at="2014-06-19T03:44:34Z" finished-at="2014-06-19T03:44:34Z">
    <groups>
      <group name="BTest">
        <method signature="BTest.divTest()[pri:0, instance:Testing.BTest@42e020c9]" name="divTest" class="Testing.BTest"/>
        <method signature="BTest.mulTest()[pri:0, instance:Testing.BTest@42e020c9]" name="mulTest" class="Testing.BTest"/>
      </group> <!-- BTest -->
    </groups>
    <test name="Default test" duration-ms="52" started-at="2014-06-19T03:44:34Z" finished-at="2014-06-19T03:44:34Z">
      <class name="Testing.BTest">
        <test-method status="PASS" signature="setUp()[pri:0, instance:Testing.BTest@42e020c9]" name="setUp" is-config="true" duration-ms="18" started-at="2014-06-19T10:44:34Z" finished-at="2014-06-19T10:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setUp -->
        <test-method status="PASS" signature="divTest()[pri:0, instance:Testing.BTest@42e020c9]" name="divTest" duration-ms="17" started-at="2014-06-19T10:44:34Z" finished-at="2014-06-19T10:44:34Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- divTest -->
        <test-method status="FAIL" signature="mulTest()[pri:0, instance:Testing.BTest@42e020c9]" name="mulTest" duration-ms="1" started-at="2014-06-19T10:44:34Z" finished-at="2014-06-19T10:44:34Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[Salah expected [150.0] but found [50.0]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: Salah expected [150.0] but found [50.0]
	at org.testng.Assert.fail(Assert.java:94)
	at org.testng.Assert.failNotEquals(Assert.java:494)
	at org.testng.Assert.assertEquals(Assert.java:123)
	at Testing.BTest.mulTest(BTest.java:27)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
	at java.lang.reflect.Method.invoke(Method.java:597)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- mulTest -->
      </class> <!-- Testing.BTest -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
